services:
  - type: web
    name: ocean-path-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
